application: ns-dev
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin
  
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  
- url: /event/notify/
  script: djangoappengine/main/main.py
  secure: always
  login: admin
  
- url: /report/notify/
  script: djangoappengine/main/main.py
  secure: always
  login: admin
  
- url: /user/remove_inactive_users/
  script: djangoappengine/main/main.py
  secure: always
  login: admin

- url: /.*
  script: djangoappengine/main/main.py
